/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MyWindow (void);
GtkWidget* create_admin (void);
GtkWidget* create_add (void);
GtkWidget* create_userlist (void);
GtkWidget* create_staff_add (void);
GtkWidget* create_stafflist (void);
GtkWidget* create_mod_user (void);
GtkWidget* create_mod_st (void);
GtkWidget* create_kine (void);
GtkWidget* create_sceance_kine (void);
GtkWidget* create_profile_kine (void);
GtkWidget* create_ajouter_seance_kine (void);
GtkWidget* create_modifier_seance_kine (void);
GtkWidget* create_coach (void);
GtkWidget* create_coach_seance (void);
GtkWidget* create_coach_ajout (void);
GtkWidget* create_coach_profil (void);
GtkWidget* create_modifier_coach (void);
