/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_MyWindow (void)
{
  GtkWidget *MyWindow;
  GtkWidget *fixed1;
  GtkWidget *username;
  GtkWidget *pass;
  GtkWidget *status;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *login;
  GtkWidget *quit;

  MyWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MyWindow, 500, 300);
  gtk_window_set_title (GTK_WINDOW (MyWindow), _("Login"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (MyWindow), fixed1);
  gtk_widget_set_size_request (fixed1, 340, 242);

  username = gtk_entry_new ();
  gtk_widget_show (username);
  gtk_fixed_put (GTK_FIXED (fixed1), username, 232, 72);
  gtk_widget_set_size_request (username, 172, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (username), 9679);

  pass = gtk_entry_new ();
  gtk_widget_show (pass);
  gtk_fixed_put (GTK_FIXED (fixed1), pass, 232, 128);
  gtk_widget_set_size_request (pass, 172, 35);
  gtk_entry_set_visibility (GTK_ENTRY (pass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (pass), 9679);

  status = gtk_label_new (_("hello"));
  gtk_widget_show (status);
  gtk_fixed_put (GTK_FIXED (fixed1), status, 104, 32);
  gtk_widget_set_size_request (status, 284, 16);

  label1 = gtk_label_new (_("Username"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 72, 80);
  gtk_widget_set_size_request (label1, 104, 16);

  label2 = gtk_label_new (_("Password"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 80, 144);
  gtk_widget_set_size_request (label2, 96, 16);

  login = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (login);
  gtk_fixed_put (GTK_FIXED (fixed1), login, 152, 208);
  gtk_widget_set_size_request (login, 71, 34);

  quit = gtk_button_new_with_mnemonic (_("Quit"));
  gtk_widget_show (quit);
  gtk_fixed_put (GTK_FIXED (fixed1), quit, 256, 208);
  gtk_widget_set_size_request (quit, 70, 33);

  g_signal_connect ((gpointer) login, "clicked",
                    G_CALLBACK (on_login_clicked),
                    NULL);
  g_signal_connect ((gpointer) quit, "clicked",
                    G_CALLBACK (on_quit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MyWindow, MyWindow, "MyWindow");
  GLADE_HOOKUP_OBJECT (MyWindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (MyWindow, username, "username");
  GLADE_HOOKUP_OBJECT (MyWindow, pass, "pass");
  GLADE_HOOKUP_OBJECT (MyWindow, status, "status");
  GLADE_HOOKUP_OBJECT (MyWindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (MyWindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (MyWindow, login, "login");
  GLADE_HOOKUP_OBJECT (MyWindow, quit, "quit");

  return MyWindow;
}

GtkWidget*
create_admin (void)
{
  GtkWidget *admin;
  GtkWidget *fixed2;
  GtkWidget *logout;
  GtkWidget *text;
  GtkWidget *label26;
  GtkWidget *users;
  GtkWidget *staff;

  admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (admin, 500, 300);
  gtk_window_set_title (GTK_WINDOW (admin), _("window1"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (admin), fixed2);

  logout = gtk_button_new_with_mnemonic (_("logout"));
  gtk_widget_show (logout);
  gtk_fixed_put (GTK_FIXED (fixed2), logout, 24, 256);
  gtk_widget_set_size_request (logout, 65, 28);

  text = gtk_label_new (_("Bonjour, admin"));
  gtk_widget_show (text);
  gtk_fixed_put (GTK_FIXED (fixed2), text, 0, 0);
  gtk_widget_set_size_request (text, 144, 40);

  label26 = gtk_label_new_with_mnemonic (_("Gestion Utilisateur"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed2), label26, 72, 56);
  gtk_widget_set_size_request (label26, 136, 24);
  gtk_label_set_line_wrap (GTK_LABEL (label26), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label26), 0.48, 0.5);

  users = gtk_button_new_with_mnemonic (_("Les adh\303\251rent"));
  gtk_widget_show (users);
  gtk_fixed_put (GTK_FIXED (fixed2), users, 72, 96);
  gtk_widget_set_size_request (users, 128, 32);

  staff = gtk_button_new_with_mnemonic (_("Le staff medical"));
  gtk_widget_show (staff);
  gtk_fixed_put (GTK_FIXED (fixed2), staff, 72, 136);
  gtk_widget_set_size_request (staff, 128, 32);
  gtk_container_set_border_width (GTK_CONTAINER (staff), 1);

  g_signal_connect ((gpointer) logout, "clicked",
                    G_CALLBACK (on_logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) users, "clicked",
                    G_CALLBACK (on_users_clicked),
                    NULL);
  g_signal_connect ((gpointer) staff, "clicked",
                    G_CALLBACK (on_staff_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admin, admin, "admin");
  GLADE_HOOKUP_OBJECT (admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (admin, logout, "logout");
  GLADE_HOOKUP_OBJECT (admin, text, "text");
  GLADE_HOOKUP_OBJECT (admin, label26, "label26");
  GLADE_HOOKUP_OBJECT (admin, users, "users");
  GLADE_HOOKUP_OBJECT (admin, staff, "staff");

  return admin;
}


GtkWidget*
create_add (void)
{
  GtkWidget *add;
  GtkWidget *fixed4;
  GtkWidget *n_user;
  GtkWidget *n_pass;
  GtkWidget *nom_ad;
  GtkWidget *prenom_ad;
  GtkWidget *email_ad;
  GtkWidget *label4;
  GtkObject *day_ad_adj;
  GtkWidget *day_ad;
  GtkObject *month_ad_adj;
  GtkWidget *month_ad;
  GtkObject *year_ad_adj;
  GtkWidget *year_ad;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label8;
  GtkWidget *label5;
  GtkWidget *label9;
  GtkWidget *label13;
  GtkWidget *tel_ad;
  GtkWidget *add_new;
  GtkWidget *quit1;
  GtkWidget *status_add_ad;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label33;
  GtkWidget *cin_ad;

  add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (add, 600, 400);
  gtk_window_set_title (GTK_WINDOW (add), _("Ajouter Adh\303\251rant"));
  gtk_window_set_position (GTK_WINDOW (add), GTK_WIN_POS_CENTER_ON_PARENT);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (add), fixed4);

  n_user = gtk_entry_new ();
  gtk_widget_show (n_user);
  gtk_fixed_put (GTK_FIXED (fixed4), n_user, 168, 120);
  gtk_widget_set_size_request (n_user, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_user), 9679);

  n_pass = gtk_entry_new ();
  gtk_widget_show (n_pass);
  gtk_fixed_put (GTK_FIXED (fixed4), n_pass, 168, 200);
  gtk_widget_set_size_request (n_pass, 172, 34);
  gtk_entry_set_visibility (GTK_ENTRY (n_pass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_pass), 9679);

  nom_ad = gtk_entry_new ();
  gtk_widget_show (nom_ad);
  gtk_fixed_put (GTK_FIXED (fixed4), nom_ad, 168, 40);
  gtk_widget_set_size_request (nom_ad, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_ad), 8226);

  prenom_ad = gtk_entry_new ();
  gtk_widget_show (prenom_ad);
  gtk_fixed_put (GTK_FIXED (fixed4), prenom_ad, 168, 80);
  gtk_widget_set_size_request (prenom_ad, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom_ad), 8226);

  email_ad = gtk_entry_new ();
  gtk_widget_show (email_ad);
  gtk_fixed_put (GTK_FIXED (fixed4), email_ad, 168, 160);
  gtk_widget_set_size_request (email_ad, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (email_ad), 8226);

  label4 = gtk_label_new (_("Nom utilisateur"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed4), label4, 40, 130);
  gtk_widget_set_size_request (label4, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label4), TRUE);

  day_ad_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  day_ad = gtk_spin_button_new (GTK_ADJUSTMENT (day_ad_adj), 1, 0);
  gtk_widget_show (day_ad);
  gtk_fixed_put (GTK_FIXED (fixed4), day_ad, 168, 240);
  gtk_widget_set_size_request (day_ad, 70, 34);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (day_ad), TRUE);

  month_ad_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  month_ad = gtk_spin_button_new (GTK_ADJUSTMENT (month_ad_adj), 1, 0);
  gtk_widget_show (month_ad);
  gtk_fixed_put (GTK_FIXED (fixed4), month_ad, 280, 240);
  gtk_widget_set_size_request (month_ad, 70, 34);

  year_ad_adj = gtk_adjustment_new (1910, 1910, 2018, 1, 10, 10);
  year_ad = gtk_spin_button_new (GTK_ADJUSTMENT (year_ad_adj), 1, 0);
  gtk_widget_show (year_ad);
  gtk_fixed_put (GTK_FIXED (fixed4), year_ad, 392, 240);
  gtk_widget_set_size_request (year_ad, 70, 34);

  label10 = gtk_label_new (_("jour"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed4), label10, 224, 248);
  gtk_widget_set_size_request (label10, 57, 16);

  label11 = gtk_label_new (_("mois"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed4), label11, 344, 248);
  gtk_widget_set_size_request (label11, 49, 17);

  label12 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 464, 248);
  gtk_widget_set_size_request (label12, 49, 17);

  label8 = gtk_label_new (_("Email"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed4), label8, 40, 170);
  gtk_widget_set_size_request (label8, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label8), TRUE);

  label5 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed4), label5, 40, 210);
  gtk_widget_set_size_request (label5, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label5), TRUE);

  label9 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed4), label9, 40, 250);
  gtk_widget_set_size_request (label9, 120, 17);
  gtk_label_set_line_wrap (GTK_LABEL (label9), TRUE);

  label13 = gtk_label_new (_("N\302\260 Telephone"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 40, 290);
  gtk_widget_set_size_request (label13, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label13), TRUE);

  tel_ad = gtk_entry_new ();
  gtk_widget_show (tel_ad);
  gtk_fixed_put (GTK_FIXED (fixed4), tel_ad, 168, 280);
  gtk_widget_set_size_request (tel_ad, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (tel_ad), 8226);

  add_new = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (add_new);
  gtk_fixed_put (GTK_FIXED (fixed4), add_new, 344, 360);
  gtk_widget_set_size_request (add_new, 65, 28);

  quit1 = gtk_button_new_with_mnemonic (_("Sortir"));
  gtk_widget_show (quit1);
  gtk_fixed_put (GTK_FIXED (fixed4), quit1, 424, 360);
  gtk_widget_set_size_request (quit1, 65, 28);

  status_add_ad = gtk_label_new ("");
  gtk_widget_show (status_add_ad);
  gtk_fixed_put (GTK_FIXED (fixed4), status_add_ad, 32, 344);
  gtk_widget_set_size_request (status_add_ad, 256, 48);

  label6 = gtk_label_new (_("Nom"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed4), label6, 40, 50);
  gtk_widget_set_size_request (label6, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label6), TRUE);
  gtk_misc_set_padding (GTK_MISC (label6), 0, 1);

  label7 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed4), label7, 40, 90);
  gtk_widget_set_size_request (label7, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label7), TRUE);

  label33 = gtk_label_new (_("Cin"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 40, 336);
  gtk_widget_set_size_request (label33, 49, 17);

  cin_ad = gtk_entry_new ();
  gtk_widget_show (cin_ad);
  gtk_fixed_put (GTK_FIXED (fixed4), cin_ad, 168, 320);
  gtk_widget_set_size_request (cin_ad, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin_ad), 8226);

  g_signal_connect ((gpointer) add_new, "clicked",
                    G_CALLBACK (on_add_new_clicked),
                    NULL);
  g_signal_connect ((gpointer) quit1, "clicked",
                    G_CALLBACK (on_quit1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (add, add, "add");
  GLADE_HOOKUP_OBJECT (add, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (add, n_user, "n_user");
  GLADE_HOOKUP_OBJECT (add, n_pass, "n_pass");
  GLADE_HOOKUP_OBJECT (add, nom_ad, "nom_ad");
  GLADE_HOOKUP_OBJECT (add, prenom_ad, "prenom_ad");
  GLADE_HOOKUP_OBJECT (add, email_ad, "email_ad");
  GLADE_HOOKUP_OBJECT (add, label4, "label4");
  GLADE_HOOKUP_OBJECT (add, day_ad, "day_ad");
  GLADE_HOOKUP_OBJECT (add, month_ad, "month_ad");
  GLADE_HOOKUP_OBJECT (add, year_ad, "year_ad");
  GLADE_HOOKUP_OBJECT (add, label10, "label10");
  GLADE_HOOKUP_OBJECT (add, label11, "label11");
  GLADE_HOOKUP_OBJECT (add, label12, "label12");
  GLADE_HOOKUP_OBJECT (add, label8, "label8");
  GLADE_HOOKUP_OBJECT (add, label5, "label5");
  GLADE_HOOKUP_OBJECT (add, label9, "label9");
  GLADE_HOOKUP_OBJECT (add, label13, "label13");
  GLADE_HOOKUP_OBJECT (add, tel_ad, "tel_ad");
  GLADE_HOOKUP_OBJECT (add, add_new, "add_new");
  GLADE_HOOKUP_OBJECT (add, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (add, status_add_ad, "status_add_ad");
  GLADE_HOOKUP_OBJECT (add, label6, "label6");
  GLADE_HOOKUP_OBJECT (add, label7, "label7");
  GLADE_HOOKUP_OBJECT (add, label33, "label33");
  GLADE_HOOKUP_OBJECT (add, cin_ad, "cin_ad");

  return add;
}

GtkWidget*
create_userlist (void)
{
  GtkWidget *userlist;
  GtkWidget *fixed5;
  GtkWidget *scrolledwindow1;
  GtkWidget *users_list;
  GtkWidget *add;
  GtkWidget *user_list_exit;

  userlist = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (userlist, 1366, 768);
  gtk_window_set_title (GTK_WINDOW (userlist), _("Liste Adh\303\251rants"));
  gtk_window_set_position (GTK_WINDOW (userlist), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (userlist), fixed5);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 8, 16);
  gtk_widget_set_size_request (scrolledwindow1, 1200, 600);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  users_list = gtk_tree_view_new ();
  gtk_widget_show (users_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), users_list);

  add = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (add);
  gtk_fixed_put (GTK_FIXED (fixed5), add, 1248, 24);
  gtk_widget_set_size_request (add, 102, 33);

  user_list_exit = gtk_button_new_with_mnemonic (_("sortir"));
  gtk_widget_show (user_list_exit);
  gtk_fixed_put (GTK_FIXED (fixed5), user_list_exit, 1248, 72);
  gtk_widget_set_size_request (user_list_exit, 102, 33);

  g_signal_connect ((gpointer) users_list, "row_activated",
                    G_CALLBACK (on_users_list_row_activated),
                    NULL);
  g_signal_connect ((gpointer) add, "clicked",
                    G_CALLBACK (on_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) user_list_exit, "clicked",
                    G_CALLBACK (on_user_list_exit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (userlist, userlist, "userlist");
  GLADE_HOOKUP_OBJECT (userlist, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (userlist, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (userlist, users_list, "users_list");
  GLADE_HOOKUP_OBJECT (userlist, add, "add");
  GLADE_HOOKUP_OBJECT (userlist, user_list_exit, "user_list_exit");

  return userlist;
}

GtkWidget*
create_staff_add (void)
{
  GtkWidget *staff_add;
  GtkWidget *fixed6;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *nom_st;
  GtkWidget *prenom_st;
  GtkWidget *username_st;
  GtkWidget *email_st;
  GtkWidget *pass_st;
  GtkWidget *tel_st;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *role;
  GtkObject *day_st_adj;
  GtkWidget *day_st;
  GtkObject *month_st_adj;
  GtkWidget *month_st;
  GtkObject *year_st_adj;
  GtkWidget *year_st;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *quit_st;
  GtkWidget *add_new_st;
  GtkWidget *label35;
  GtkWidget *cin_st;

  staff_add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (staff_add, 600, 400);
  gtk_window_set_title (GTK_WINDOW (staff_add), _("Ajouter Staff"));
  gtk_window_set_position (GTK_WINDOW (staff_add), GTK_WIN_POS_CENTER_ON_PARENT);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (staff_add), fixed6);
  gtk_container_set_border_width (GTK_CONTAINER (fixed6), 10);

  label15 = gtk_label_new (_("Nom"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed6), label15, 40, 20);
  gtk_widget_set_size_request (label15, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label15), TRUE);

  label16 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed6), label16, 40, 60);
  gtk_widget_set_size_request (label16, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label16), TRUE);

  label17 = gtk_label_new (_("Nom Utilisateur"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed6), label17, 40, 100);
  gtk_widget_set_size_request (label17, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label17), TRUE);

  label18 = gtk_label_new (_("Email"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed6), label18, 40, 140);
  gtk_widget_set_size_request (label18, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label18), TRUE);

  label19 = gtk_label_new (_("Mot de pass"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed6), label19, 40, 180);
  gtk_widget_set_size_request (label19, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed6), label20, 40, 220);
  gtk_widget_set_size_request (label20, 120, 16);

  nom_st = gtk_entry_new ();
  gtk_widget_show (nom_st);
  gtk_fixed_put (GTK_FIXED (fixed6), nom_st, 168, 10);
  gtk_widget_set_size_request (nom_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_st), 8226);

  prenom_st = gtk_entry_new ();
  gtk_widget_show (prenom_st);
  gtk_fixed_put (GTK_FIXED (fixed6), prenom_st, 168, 50);
  gtk_widget_set_size_request (prenom_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom_st), 8226);

  username_st = gtk_entry_new ();
  gtk_widget_show (username_st);
  gtk_fixed_put (GTK_FIXED (fixed6), username_st, 168, 90);
  gtk_widget_set_size_request (username_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (username_st), 8226);

  email_st = gtk_entry_new ();
  gtk_widget_show (email_st);
  gtk_fixed_put (GTK_FIXED (fixed6), email_st, 168, 130);
  gtk_widget_set_size_request (email_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (email_st), 8226);

  pass_st = gtk_entry_new ();
  gtk_widget_show (pass_st);
  gtk_fixed_put (GTK_FIXED (fixed6), pass_st, 168, 170);
  gtk_widget_set_size_request (pass_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (pass_st), 8226);

  tel_st = gtk_entry_new ();
  gtk_widget_show (tel_st);
  gtk_fixed_put (GTK_FIXED (fixed6), tel_st, 168, 250);
  gtk_widget_set_size_request (tel_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (tel_st), 8226);

  label21 = gtk_label_new (_("N\302\260 Telephone"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed6), label21, 40, 260);
  gtk_widget_set_size_request (label21, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label21), TRUE);

  label22 = gtk_label_new (_("Role"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed6), label22, 40, 300);
  gtk_widget_set_size_request (label22, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label22), TRUE);

  role = gtk_combo_box_new_text ();
  gtk_widget_show (role);
  gtk_fixed_put (GTK_FIXED (fixed6), role, 168, 290);
  gtk_widget_set_size_request (role, 170, 34);
  gtk_container_set_border_width (GTK_CONTAINER (role), 1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (role), _("Coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (role), _("Dieteticien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (role), _("Kine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (role), _("Medecin"));

  day_st_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  day_st = gtk_spin_button_new (GTK_ADJUSTMENT (day_st_adj), 1, 0);
  gtk_widget_show (day_st);
  gtk_fixed_put (GTK_FIXED (fixed6), day_st, 168, 208);
  gtk_widget_set_size_request (day_st, 70, 34);

  month_st_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  month_st = gtk_spin_button_new (GTK_ADJUSTMENT (month_st_adj), 1, 0);
  gtk_widget_show (month_st);
  gtk_fixed_put (GTK_FIXED (fixed6), month_st, 288, 208);
  gtk_widget_set_size_request (month_st, 70, 34);

  year_st_adj = gtk_adjustment_new (1910, 1910, 2018, 1, 10, 10);
  year_st = gtk_spin_button_new (GTK_ADJUSTMENT (year_st_adj), 1, 0);
  gtk_widget_show (year_st);
  gtk_fixed_put (GTK_FIXED (fixed6), year_st, 400, 208);
  gtk_widget_set_size_request (year_st, 70, 34);

  label23 = gtk_label_new (_("Jour"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed6), label23, 240, 216);
  gtk_widget_set_size_request (label23, 49, 17);
  gtk_label_set_line_wrap (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new (_("Mois"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed6), label24, 360, 216);
  gtk_widget_set_size_request (label24, 49, 17);
  gtk_label_set_line_wrap (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed6), label25, 472, 216);
  gtk_widget_set_size_request (label25, 49, 17);
  gtk_label_set_line_wrap (GTK_LABEL (label25), TRUE);

  quit_st = gtk_button_new_with_mnemonic (_("Sortir"));
  gtk_widget_show (quit_st);
  gtk_fixed_put (GTK_FIXED (fixed6), quit_st, 472, 352);
  gtk_widget_set_size_request (quit_st, 70, 33);

  add_new_st = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (add_new_st);
  gtk_fixed_put (GTK_FIXED (fixed6), add_new_st, 376, 352);
  gtk_widget_set_size_request (add_new_st, 70, 33);

  label35 = gtk_label_new (_("cin"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 24, 328);
  gtk_widget_set_size_request (label35, 49, 17);

  cin_st = gtk_entry_new ();
  gtk_widget_show (cin_st);
  gtk_fixed_put (GTK_FIXED (fixed6), cin_st, 168, 328);
  gtk_widget_set_size_request (cin_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin_st), 8226);

  g_signal_connect ((gpointer) quit_st, "clicked",
                    G_CALLBACK (on_quit_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) add_new_st, "clicked",
                    G_CALLBACK (on_add_new_st_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (staff_add, staff_add, "staff_add");
  GLADE_HOOKUP_OBJECT (staff_add, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (staff_add, label15, "label15");
  GLADE_HOOKUP_OBJECT (staff_add, label16, "label16");
  GLADE_HOOKUP_OBJECT (staff_add, label17, "label17");
  GLADE_HOOKUP_OBJECT (staff_add, label18, "label18");
  GLADE_HOOKUP_OBJECT (staff_add, label19, "label19");
  GLADE_HOOKUP_OBJECT (staff_add, label20, "label20");
  GLADE_HOOKUP_OBJECT (staff_add, nom_st, "nom_st");
  GLADE_HOOKUP_OBJECT (staff_add, prenom_st, "prenom_st");
  GLADE_HOOKUP_OBJECT (staff_add, username_st, "username_st");
  GLADE_HOOKUP_OBJECT (staff_add, email_st, "email_st");
  GLADE_HOOKUP_OBJECT (staff_add, pass_st, "pass_st");
  GLADE_HOOKUP_OBJECT (staff_add, tel_st, "tel_st");
  GLADE_HOOKUP_OBJECT (staff_add, label21, "label21");
  GLADE_HOOKUP_OBJECT (staff_add, label22, "label22");
  GLADE_HOOKUP_OBJECT (staff_add, role, "role");
  GLADE_HOOKUP_OBJECT (staff_add, day_st, "day_st");
  GLADE_HOOKUP_OBJECT (staff_add, month_st, "month_st");
  GLADE_HOOKUP_OBJECT (staff_add, year_st, "year_st");
  GLADE_HOOKUP_OBJECT (staff_add, label23, "label23");
  GLADE_HOOKUP_OBJECT (staff_add, label24, "label24");
  GLADE_HOOKUP_OBJECT (staff_add, label25, "label25");
  GLADE_HOOKUP_OBJECT (staff_add, quit_st, "quit_st");
  GLADE_HOOKUP_OBJECT (staff_add, add_new_st, "add_new_st");
  GLADE_HOOKUP_OBJECT (staff_add, label35, "label35");
  GLADE_HOOKUP_OBJECT (staff_add, cin_st, "cin_st");

  return staff_add;
}

GtkWidget*
create_stafflist (void)
{
  GtkWidget *stafflist;
  GtkWidget *fixed7;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *add_st;
  GtkWidget *quit_st_list;

  stafflist = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (stafflist, 1366, 700);
  gtk_window_set_title (GTK_WINDOW (stafflist), _("Staff Medical"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (stafflist), fixed7);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow2, 8, 8);
  gtk_widget_set_size_request (scrolledwindow2, 1200, 600);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);

  add_st = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (add_st);
  gtk_fixed_put (GTK_FIXED (fixed7), add_st, 1256, 32);
  gtk_widget_set_size_request (add_st, 104, 32);

  quit_st_list = gtk_button_new_with_mnemonic (_("Sortir"));
  gtk_widget_show (quit_st_list);
  gtk_fixed_put (GTK_FIXED (fixed7), quit_st_list, 1256, 88);
  gtk_widget_set_size_request (quit_st_list, 104, 32);

  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) add_st, "clicked",
                    G_CALLBACK (on_add_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) quit_st_list, "clicked",
                    G_CALLBACK (on_quit_st_list_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (stafflist, stafflist, "stafflist");
  GLADE_HOOKUP_OBJECT (stafflist, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (stafflist, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (stafflist, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (stafflist, add_st, "add_st");
  GLADE_HOOKUP_OBJECT (stafflist, quit_st_list, "quit_st_list");

  return stafflist;
}

GtkWidget*
create_mod_user (void)
{
  GtkWidget *mod_user;
  GtkWidget *fixed8;
  GtkWidget *mod_name;
  GtkWidget *mod_prenom;
  GtkWidget *mod_login;
  GtkWidget *mod_pass;
  GtkWidget *mod_tel;
  GtkWidget *mod_email;
  GtkWidget *mod_cin;
  GtkWidget *label32;
  GtkWidget *label31;
  GtkWidget *_;
  GtkWidget *log_l;
  GtkWidget *nom_l;
  GtkWidget *user_l;
  GtkWidget *label34;
  GtkWidget *mod_user_btn;
  GtkWidget *mod_user_exit;

  mod_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mod_user), _("Modifier Informton Personnelles"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (mod_user), fixed8);

  mod_name = gtk_entry_new ();
  gtk_widget_show (mod_name);
  gtk_fixed_put (GTK_FIXED (fixed8), mod_name, 128, 72);
  gtk_widget_set_size_request (mod_name, 172, 34);
  gtk_entry_set_text (GTK_ENTRY (mod_name), _("hello"));
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_name), 8226);

  mod_prenom = gtk_entry_new ();
  gtk_widget_show (mod_prenom);
  gtk_fixed_put (GTK_FIXED (fixed8), mod_prenom, 128, 120);
  gtk_widget_set_size_request (mod_prenom, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_prenom), 8226);

  mod_login = gtk_entry_new ();
  gtk_widget_show (mod_login);
  gtk_fixed_put (GTK_FIXED (fixed8), mod_login, 128, 168);
  gtk_widget_set_size_request (mod_login, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_login), 8226);

  mod_pass = gtk_entry_new ();
  gtk_widget_show (mod_pass);
  gtk_fixed_put (GTK_FIXED (fixed8), mod_pass, 128, 216);
  gtk_widget_set_size_request (mod_pass, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_pass), 8226);

  mod_tel = gtk_entry_new ();
  gtk_widget_show (mod_tel);
  gtk_fixed_put (GTK_FIXED (fixed8), mod_tel, 128, 264);
  gtk_widget_set_size_request (mod_tel, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_tel), 8226);

  mod_email = gtk_entry_new ();
  gtk_widget_show (mod_email);
  gtk_fixed_put (GTK_FIXED (fixed8), mod_email, 128, 312);
  gtk_widget_set_size_request (mod_email, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_email), 8226);

  mod_cin = gtk_entry_new ();
  gtk_widget_show (mod_cin);
  gtk_fixed_put (GTK_FIXED (fixed8), mod_cin, 128, 24);
  gtk_widget_set_size_request (mod_cin, 172, 34);
  gtk_editable_set_editable (GTK_EDITABLE (mod_cin), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_cin), 8226);

  label32 = gtk_label_new (_("email"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed8), label32, 32, 320);
  gtk_widget_set_size_request (label32, 49, 17);

  label31 = gtk_label_new (_("tel"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed8), label31, 24, 272);
  gtk_widget_set_size_request (label31, 49, 17);

  _ = gtk_label_new (_("mot de passe"));
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed8), _, 24, 216);
  gtk_widget_set_size_request (_, 104, 24);

  log_l = gtk_label_new (_("login"));
  gtk_widget_show (log_l);
  gtk_fixed_put (GTK_FIXED (fixed8), log_l, 24, 176);
  gtk_widget_set_size_request (log_l, 49, 17);

  nom_l = gtk_label_new (_("prenom"));
  gtk_widget_show (nom_l);
  gtk_fixed_put (GTK_FIXED (fixed8), nom_l, 24, 120);
  gtk_widget_set_size_request (nom_l, 72, 24);

  user_l = gtk_label_new (_("Nom"));
  gtk_widget_show (user_l);
  gtk_fixed_put (GTK_FIXED (fixed8), user_l, 16, 80);
  gtk_widget_set_size_request (user_l, 64, 16);

  label34 = gtk_label_new (_("Cin"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed8), label34, 8, 32);
  gtk_widget_set_size_request (label34, 64, 24);

  mod_user_btn = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (mod_user_btn);
  gtk_fixed_put (GTK_FIXED (fixed8), mod_user_btn, 288, 384);
  gtk_widget_set_size_request (mod_user_btn, 70, 33);

  mod_user_exit = gtk_button_new_with_mnemonic (_("sortir"));
  gtk_widget_show (mod_user_exit);
  gtk_fixed_put (GTK_FIXED (fixed8), mod_user_exit, 376, 384);
  gtk_widget_set_size_request (mod_user_exit, 70, 33);

  g_signal_connect ((gpointer) mod_user_btn, "clicked",
                    G_CALLBACK (on_mod_user_btn_clicked),
                    NULL);
  g_signal_connect ((gpointer) mod_user_exit, "clicked",
                    G_CALLBACK (on_mod_user_exit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mod_user, mod_user, "mod_user");
  GLADE_HOOKUP_OBJECT (mod_user, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (mod_user, mod_name, "mod_name");
  GLADE_HOOKUP_OBJECT (mod_user, mod_prenom, "mod_prenom");
  GLADE_HOOKUP_OBJECT (mod_user, mod_login, "mod_login");
  GLADE_HOOKUP_OBJECT (mod_user, mod_pass, "mod_pass");
  GLADE_HOOKUP_OBJECT (mod_user, mod_tel, "mod_tel");
  GLADE_HOOKUP_OBJECT (mod_user, mod_email, "mod_email");
  GLADE_HOOKUP_OBJECT (mod_user, mod_cin, "mod_cin");
  GLADE_HOOKUP_OBJECT (mod_user, label32, "label32");
  GLADE_HOOKUP_OBJECT (mod_user, label31, "label31");
  GLADE_HOOKUP_OBJECT (mod_user, _, "_");
  GLADE_HOOKUP_OBJECT (mod_user, log_l, "log_l");
  GLADE_HOOKUP_OBJECT (mod_user, nom_l, "nom_l");
  GLADE_HOOKUP_OBJECT (mod_user, user_l, "user_l");
  GLADE_HOOKUP_OBJECT (mod_user, label34, "label34");
  GLADE_HOOKUP_OBJECT (mod_user, mod_user_btn, "mod_user_btn");
  GLADE_HOOKUP_OBJECT (mod_user, mod_user_exit, "mod_user_exit");

  return mod_user;
}

GtkWidget*
create_mod_st (void)
{
  GtkWidget *mod_st;
  GtkWidget *fixed9;
  GtkWidget *mod_cin_st;
  GtkWidget *mod_name_st;
  GtkWidget *mod_prenom_st;
  GtkWidget *mod_login_st;
  GtkWidget *mod_pass_st;
  GtkWidget *mod_tel_st;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *mod_email_st;
  GtkWidget *mod_st_exit;
  GtkWidget *mod_st_btn;

  mod_st = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mod_st), _("Modifier information Staff"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (mod_st), fixed9);

  mod_cin_st = gtk_entry_new ();
  gtk_widget_show (mod_cin_st);
  gtk_fixed_put (GTK_FIXED (fixed9), mod_cin_st, 144, 24);
  gtk_widget_set_size_request (mod_cin_st, 172, 34);
  GTK_WIDGET_UNSET_FLAGS (mod_cin_st, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (mod_cin_st), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_cin_st), 8226);

  mod_name_st = gtk_entry_new ();
  gtk_widget_show (mod_name_st);
  gtk_fixed_put (GTK_FIXED (fixed9), mod_name_st, 144, 72);
  gtk_widget_set_size_request (mod_name_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_name_st), 8226);

  mod_prenom_st = gtk_entry_new ();
  gtk_widget_show (mod_prenom_st);
  gtk_fixed_put (GTK_FIXED (fixed9), mod_prenom_st, 144, 120);
  gtk_widget_set_size_request (mod_prenom_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_prenom_st), 8226);

  mod_login_st = gtk_entry_new ();
  gtk_widget_show (mod_login_st);
  gtk_fixed_put (GTK_FIXED (fixed9), mod_login_st, 144, 168);
  gtk_widget_set_size_request (mod_login_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_login_st), 8226);

  mod_pass_st = gtk_entry_new ();
  gtk_widget_show (mod_pass_st);
  gtk_fixed_put (GTK_FIXED (fixed9), mod_pass_st, 144, 216);
  gtk_widget_set_size_request (mod_pass_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_pass_st), 8226);

  mod_tel_st = gtk_entry_new ();
  gtk_widget_show (mod_tel_st);
  gtk_fixed_put (GTK_FIXED (fixed9), mod_tel_st, 144, 264);
  gtk_widget_set_size_request (mod_tel_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_tel_st), 8226);

  label36 = gtk_label_new (_("cin"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed9), label36, 16, 32);
  gtk_widget_set_size_request (label36, 49, 17);

  label37 = gtk_label_new (_("nom"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed9), label37, 24, 80);
  gtk_widget_set_size_request (label37, 49, 17);

  label38 = gtk_label_new (_("prenom"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed9), label38, 32, 128);
  gtk_widget_set_size_request (label38, 49, 17);

  label39 = gtk_label_new (_("login"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed9), label39, 24, 176);
  gtk_widget_set_size_request (label39, 49, 17);

  label40 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed9), label40, 32, 224);
  gtk_widget_set_size_request (label40, 96, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label40), TRUE);

  label41 = gtk_label_new (_("tel"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed9), label41, 16, 272);
  gtk_widget_set_size_request (label41, 49, 17);

  label42 = gtk_label_new (_("email"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed9), label42, 24, 320);
  gtk_widget_set_size_request (label42, 49, 17);

  mod_email_st = gtk_entry_new ();
  gtk_widget_show (mod_email_st);
  gtk_fixed_put (GTK_FIXED (fixed9), mod_email_st, 144, 312);
  gtk_widget_set_size_request (mod_email_st, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod_email_st), 8226);

  mod_st_exit = gtk_button_new_with_mnemonic (_("sortir"));
  gtk_widget_show (mod_st_exit);
  gtk_fixed_put (GTK_FIXED (fixed9), mod_st_exit, 320, 376);
  gtk_widget_set_size_request (mod_st_exit, 70, 33);

  mod_st_btn = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (mod_st_btn);
  gtk_fixed_put (GTK_FIXED (fixed9), mod_st_btn, 232, 376);
  gtk_widget_set_size_request (mod_st_btn, 70, 33);

  g_signal_connect ((gpointer) mod_st_exit, "clicked",
                    G_CALLBACK (on_mod_st_exit_clicked),
                    NULL);
  g_signal_connect ((gpointer) mod_st_btn, "clicked",
                    G_CALLBACK (on_mod_st_btn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mod_st, mod_st, "mod_st");
  GLADE_HOOKUP_OBJECT (mod_st, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (mod_st, mod_cin_st, "mod_cin_st");
  GLADE_HOOKUP_OBJECT (mod_st, mod_name_st, "mod_name_st");
  GLADE_HOOKUP_OBJECT (mod_st, mod_prenom_st, "mod_prenom_st");
  GLADE_HOOKUP_OBJECT (mod_st, mod_login_st, "mod_login_st");
  GLADE_HOOKUP_OBJECT (mod_st, mod_pass_st, "mod_pass_st");
  GLADE_HOOKUP_OBJECT (mod_st, mod_tel_st, "mod_tel_st");
  GLADE_HOOKUP_OBJECT (mod_st, label36, "label36");
  GLADE_HOOKUP_OBJECT (mod_st, label37, "label37");
  GLADE_HOOKUP_OBJECT (mod_st, label38, "label38");
  GLADE_HOOKUP_OBJECT (mod_st, label39, "label39");
  GLADE_HOOKUP_OBJECT (mod_st, label40, "label40");
  GLADE_HOOKUP_OBJECT (mod_st, label41, "label41");
  GLADE_HOOKUP_OBJECT (mod_st, label42, "label42");
  GLADE_HOOKUP_OBJECT (mod_st, mod_email_st, "mod_email_st");
  GLADE_HOOKUP_OBJECT (mod_st, mod_st_exit, "mod_st_exit");
  GLADE_HOOKUP_OBJECT (mod_st, mod_st_btn, "mod_st_btn");

  return mod_st;
}

GtkWidget*
create_kine (void)
{
  GtkWidget *kine;
  GtkWidget *fixed2;
  GtkWidget *label4;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button3;

  kine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (kine), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (kine), fixed2);

  label4 = gtk_label_new (_("Bienvenue dans l'espace kin\303\251"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 80, 8);
  gtk_widget_set_size_request (label4, 240, 25);

  button4 = gtk_button_new_with_mnemonic (_("Afficher le profil"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 112, 48);
  gtk_widget_set_size_request (button4, 184, 40);

  button5 = gtk_button_new_with_mnemonic (_("Gestion des s\303\251ances de cure "));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 96, 104);
  gtk_widget_set_size_request (button5, 224, 45);

  button3 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 336, 256);
  gtk_widget_set_size_request (button3, 68, 29);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_afficher_profile_espace_kine_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_ajouter_seance_espace_kine_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_retour_espace_kine_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (kine, kine, "kine");
  GLADE_HOOKUP_OBJECT (kine, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (kine, label4, "label4");
  GLADE_HOOKUP_OBJECT (kine, button4, "button4");
  GLADE_HOOKUP_OBJECT (kine, button5, "button5");
  GLADE_HOOKUP_OBJECT (kine, button3, "button3");

  return kine;
}

GtkWidget*
create_sceance_kine (void)
{
  GtkWidget *sceance_kine;
  GtkWidget *fixed3;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *label5;
  GtkWidget *button7;
  GtkWidget *button8;

  sceance_kine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (sceance_kine, 530, 331);
  gtk_window_set_title (GTK_WINDOW (sceance_kine), _("window3"));
  gtk_window_set_destroy_with_parent (GTK_WINDOW (sceance_kine), TRUE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (sceance_kine), fixed3);
  gtk_widget_set_size_request (fixed3, 284, 187);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow1, 115, 12);
  gtk_widget_set_size_request (scrolledwindow1, 335, 202);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);

  label5 = gtk_label_new (_("les s\303\251ances de cure "));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 200, 240);
  gtk_widget_set_size_request (label5, 176, 24);
  gtk_label_set_line_wrap (GTK_LABEL (label5), TRUE);

  button7 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 336, 248);
  gtk_widget_set_size_request (button7, 68, 29);

  button8 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 416, 248);
  gtk_widget_set_size_request (button8, 68, 29);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated_kine_seance),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_ajouter_seance_kine_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_retour_seance_kine_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (sceance_kine, sceance_kine, "sceance_kine");
  GLADE_HOOKUP_OBJECT (sceance_kine, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (sceance_kine, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (sceance_kine, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (sceance_kine, label5, "label5");
  GLADE_HOOKUP_OBJECT (sceance_kine, button7, "button7");
  GLADE_HOOKUP_OBJECT (sceance_kine, button8, "button8");

  return sceance_kine;
}

GtkWidget*
create_profile_kine (void)
{
  GtkWidget *profile_kine;
  GtkWidget *fixed4;
  GtkWidget *label6;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label13;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label12;
  GtkWidget *button6;
  GtkWidget *button10;

  profile_kine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (profile_kine, 478, 261);
  gtk_window_set_title (GTK_WINDOW (profile_kine), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (profile_kine), fixed4);

  label6 = gtk_label_new (_("profile kin\303\251 "));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed4), label6, 112, 8);
  gtk_widget_set_size_request (label6, 144, 25);

  label10 = gtk_label_new (_("nom:"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed4), label10, 72, 64);
  gtk_widget_set_size_request (label10, 49, 17);

  label11 = gtk_label_new (_("prenom:"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed4), label11, 48, 96);
  gtk_widget_set_size_request (label11, 80, 24);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 160, 56);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 160, 88);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label13 = gtk_label_new (_("jour "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 144, 136);
  gtk_widget_set_size_request (label13, 49, 17);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1, 184, 128);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label14 = gtk_label_new (_("mois"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 248, 136);
  gtk_widget_set_size_request (label14, 49, 17);

  label15 = gtk_label_new (_("annee"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 360, 136);
  gtk_widget_set_size_request (label15, 56, 17);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 296, 128);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 2017, 2060, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 408, 128);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label12 = gtk_label_new (_("date de naissance:"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 8, 136);
  gtk_widget_set_size_request (label12, 144, 24);

  button6 = gtk_button_new_with_mnemonic (_("Retour "));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 400, 208);
  gtk_widget_set_size_request (button6, 68, 29);

  button10 = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed4), button10, 304, 208);
  gtk_widget_set_size_request (button10, 76, 29);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_retour_profil_kine_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (profile_kine, profile_kine, "profile_kine");
  GLADE_HOOKUP_OBJECT (profile_kine, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (profile_kine, label6, "label6");
  GLADE_HOOKUP_OBJECT (profile_kine, label10, "label10");
  GLADE_HOOKUP_OBJECT (profile_kine, label11, "label11");
  GLADE_HOOKUP_OBJECT (profile_kine, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (profile_kine, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (profile_kine, label13, "label13");
  GLADE_HOOKUP_OBJECT (profile_kine, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (profile_kine, label14, "label14");
  GLADE_HOOKUP_OBJECT (profile_kine, label15, "label15");
  GLADE_HOOKUP_OBJECT (profile_kine, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (profile_kine, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (profile_kine, label12, "label12");
  GLADE_HOOKUP_OBJECT (profile_kine, button6, "button6");
  GLADE_HOOKUP_OBJECT (profile_kine, button10, "button10");

  return profile_kine;
}

GtkWidget*
create_ajouter_seance_kine (void)
{
  GtkWidget *ajouter_seance_kine;
  GtkWidget *fixed5;
  GtkWidget *label7;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *label9;
  GtkWidget *label8;
  GtkWidget *button9;

  ajouter_seance_kine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_seance_kine), _("window5"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (ajouter_seance_kine), fixed5);

  label7 = gtk_label_new (_("nom"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 64, 56);
  gtk_widget_set_size_request (label7, 41, 17);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed5), entry3, 184, 48);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed5), entry4, 184, 88);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed5), entry5, 184, 128);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label9 = gtk_label_new (_("s\303\251ance"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed5), label9, 64, 136);
  gtk_widget_set_size_request (label9, 64, 17);

  label8 = gtk_label_new (_("prenom"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed5), label8, 48, 96);
  gtk_widget_set_size_request (label8, 88, 16);

  button9 = gtk_button_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed5), button9, 296, 176);
  gtk_widget_set_size_request (button9, 68, 29);

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_ajouter_rdv_kine_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_seance_kine, ajouter_seance_kine, "ajouter_seance_kine");
  GLADE_HOOKUP_OBJECT (ajouter_seance_kine, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (ajouter_seance_kine, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajouter_seance_kine, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (ajouter_seance_kine, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (ajouter_seance_kine, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (ajouter_seance_kine, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajouter_seance_kine, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajouter_seance_kine, button9, "button9");

  return ajouter_seance_kine;
}


GtkWidget*
create_modifier_seance_kine (void)
{
  GtkWidget *modifier_seance_kine;
  GtkWidget *fixed6;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *retour_modifier_kine;
  GtkWidget *modifier_sceance;
  GtkWidget *label19;
  GtkWidget *supprimer_seance;

  modifier_seance_kine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_seance_kine), _("window2"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (modifier_seance_kine), fixed6);

  label16 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed6), label16, 64, 104);
  gtk_widget_set_size_request (label16, 49, 17);

  label17 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed6), label17, 56, 152);
  gtk_widget_set_size_request (label17, 88, 17);

  label18 = gtk_label_new (_("sceance :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed6), label18, 64, 200);
  gtk_widget_set_size_request (label18, 80, 17);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed6), entry8, 144, 96);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed6), entry9, 144, 144);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed6), entry10, 144, 192);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  retour_modifier_kine = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retour_modifier_kine);
  gtk_fixed_put (GTK_FIXED (fixed6), retour_modifier_kine, 400, 272);
  gtk_widget_set_size_request (retour_modifier_kine, 76, 29);

  modifier_sceance = gtk_button_new_with_mnemonic (_("Modifier "));
  gtk_widget_show (modifier_sceance);
  gtk_fixed_put (GTK_FIXED (fixed6), modifier_sceance, 296, 272);
  gtk_widget_set_size_request (modifier_sceance, 76, 29);

  label19 = gtk_label_new ("");
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed6), label19, 168, 40);
  gtk_widget_set_size_request (label19, 128, 24);

  supprimer_seance = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (supprimer_seance);
  gtk_fixed_put (GTK_FIXED (fixed6), supprimer_seance, 184, 272);
  gtk_widget_set_size_request (supprimer_seance, 88, 29);

  g_signal_connect ((gpointer) retour_modifier_kine, "clicked",
                    G_CALLBACK (on_retour_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_sceance, "clicked",
                    G_CALLBACK (on_modifier_sceance_kine_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_seance, "clicked",
                    G_CALLBACK (on_supprimer_seance_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_seance_kine, modifier_seance_kine, "modifier_seance_kine");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, retour_modifier_kine, "retour_modifier_kine");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, modifier_sceance, "modifier_sceance");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifier_seance_kine, supprimer_seance, "supprimer_seance");

  return modifier_seance_kine;
}

